### ISSUE TITLE
add new tag

### ISSUE THREAD

**Issue by balagurrr** [terraform-yc-modules/terraform-yc-s3#8]
please add a tag to the master branch. version 1.0.2 does not contain the [latest changes](https://github.com/terraform-yc-modules/terraform-yc-s3/commit/baa909cf9430491ad3d6c137c7b44ffa337c2693)

**Comment by VictorEfim** [comment]
Подтверждаю, из-за этого некорректно работает права на доступ к бакету

**Comment by romati88** [comment]
1.0.3
